environment:
  PYTHON: "C:\\Python35-x64"
  PYTHON_VERSION: "3.5.2"
  PYTHON_ARCH: "64"

build: off

init:
  - "SET PYTHONPATH=%PYTHONPATH%;src;test;"
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %PYTHONPATH%"

test_script:
  - "%PYTHON%/python -m unittest discover -s test/ -p test_*.py"
